#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

echo "Drupal application credentials\n\tuser: admin\n\tpassword: openshift_changeme\n" > ${OPENSHIFT_DATA_DIR}/CREDENTIALS

#
# Install drush outside of pear for now.
#

DRUSH_URL=https://github.com/drush-ops/drush/archive/6.2.0.tar.gz 

export PATH=$PATH:${OPENSHIFT_DEPENDENCIES_DIR}/drush

if [ -z $(which drush) ]; then
  if ! [ -r $OPENSHIFT_DATA_DIR/downloads/drush.tgz ]; then
  	cd  $OPENSHIFT_DATA_DIR/downloads
    wget ${DRUSH_URL} -O drush.tgz
    cd -
  fi
  cd ${OPENSHIFT_DEPENDENCIES_DIR}
  tar xzvf $OPENSHIFT_DATA_DIR/downloads/drush.tgz 
  mv drush-* drush
  cd -

  export PATH=${OPENSHIFT_DEPENDENCIES_DIR}/drush
fi



