#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

echo "Drupal application credentials\n\tuser: admin\n\tpassword: openshift_changeme\n" > ${OPENSHIFT_DATA_DIR}/CREDENTIALS

#
# Make our own personal bin dir and add to PATH
#
mkdir -p ${OPENSHIFT_DATA_DIR}bin
rm -f ${OPENSHIFT_DATA_DIR}/.bash_profile
echo "PATH=\$PATH:${OPENSHIFT_DATA_DIR}bin" > ${OPENSHIFT_DATA_DIR}/.bash_profile
echo "export PATH" >> ${OPENSHIFT_DATA_DIR}/.bash_profile

#
# Install drush outside of pear for now.
#

DRUSH_URL=https://github.com/drush-ops/drush/archive/6.2.0.tar.gz 

[ -d $OPENSHIFT_DATA_DIR/downloads ] || mkdir $OPENSHIFT_DATA_DIR/downloads

if [ -z $(which drush 2>/dev/null ) ]; then
   if ! [ -r $OPENSHIFT_DATA_DIR/downloads/drush.tgz ]; then
   	pushd  $OPENSHIFT_DATA_DIR/downloads
     wget ${DRUSH_URL} -O drush.tgz
     popd
   fi
   pushd $OPENSHIFT_DATA_DIR/downloads
   tar xzvf $OPENSHIFT_DATA_DIR/downloads/drush.tgz 
   DRUSH_DIR=$( ls -1td drush* | grep -v tgz | head -1 )
  
   pushd ${OPENSHIFT_DATA_DIR}bin
   ln -s $OPENSHIFT_DATA_DIR/downloads/$DRUSH_DIR/drush .
   popd 
   popd
fi


#
# Install a tool to manage INI files
#
URL=https://raw2.github.com/pixelb/crudini/master/crudini
curl $URL > ${OPENSHIFT_DATA_DIR}bin/crudini
chmod +x ${OPENSHIFT_DATA_DIR}bin/crudini


